---
title: "check_annotations"
author: "Nico Bast"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    theme: cerulean
    code_folding: hide
  word_document:
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

require(ggplot2)
theme_set(theme_bw())

# ###time conversion - this function is required when onset/offset is provided as character of POSIXCT
fun_timeconv2<-function(x){
time_var<-x
time_var<-as.numeric(substr(time_var,1,2))*3600+
  as.numeric(substr(time_var,4,5))*60+
  as.numeric(substr(time_var,7,8))+
  as.numeric(substr(time_var,10,11))*0.01
return(time_var)
}

```

This R Markdown document takes an annotation export from file and generated an output that provides a technical check of the annotations  

## manual edits

```{r manual edits}

#paths
path<-'C:/Users/nico/PowerFolders/project_dynamic/video_annotations/data/FRA_038_T5_Konsens_Paula.csv'

```


## Read file

```{r file selection}

## paths
rater1<-read.csv(path,sep=';',dec=',') #PAULA


```

## Convert and select data
```{r}

#convert time data - consider whether time is provided as POXIXCT character or numeric character
if(grepl(':',rater1$Onset_Time[1])){
  rater1$Offset_Time<-fun_timeconv2(rater1$Offset_Time)
  rater1$Onset_Time<-fun_timeconv2(rater1$Onset_Time)
} else {
  rater1$Offset_Time<-as.numeric(rater1$Offset_Time)
  rater1$Onset_Time<-as.numeric(rater1$Onset_Time)
}

```

## Plot annotations for all rating category

- Figure shows the overlap of ratings 
- Annotated gaze events (x-axis) and onset and offset of that event (y-axis).

```{r plotting, echo=FALSE, fig.height=8, fig.width=10}


#combine onset and offset data with rater for plotting
rater1$seq<-1:nrow(rater1)

#select rating category columns
selected_columns<-
  names(rater1) %in% 
  c("Mutual","Avert","Refer","Follow","Share","Single.gaze")

#combine rating values to one column
rater1$ratings <- apply(rater1[,selected_columns], 1, function(x){
 return_value<-ifelse(all(nchar(x)==0),
                      NA,
                      x[nchar(x)>0])
 return(return_value)
})

#remove NA
rater1<-rater1[!is.na(rater1$ratings),]

#identify overlap
overlap_previous<-c()
for(i in 1:nrow(rater1)){
  overlap_previous[i]<-ifelse(i==1,F,
    ifelse(rater1$Onset_Time[i]<rater1$Offset_Time[i-1],T,F))
}
overlap_next<-c()
for(i in 1:nrow(rater1)){
  overlap_next[i]<-ifelse(i==nrow(rater1),F,
    ifelse(rater1$Offset_Time[i]>rater1$Onset_Time[i+1],T,F))
}

rater1$overlap<-overlap_next|overlap_previous


#split figures by minute
rater1$minute<-floor(rater1$Offset_Time/60)

unique_rating_minutes<-unique(rater1$minute)
gg_list<-list()
for (i in 1:length(unique_rating_minutes)) {
  gg_list[[i]]<-ggplot(rater1[rater1$minute==unique_rating_minutes[i] & rater1$overlap,]) +
    geom_segment(aes(x = seq, xend = seq, y = Onset_Time/60, yend = Offset_Time/60,color=ratings,linewidth=2)) +
    labs(title = paste("ratings of minute",unique_rating_minutes[i]), 
         x = "annotation number",
         y = "annotation duration (min)")
}

#print
gg_list[1:length(gg_list)]

```


